[Log]
Level = 'warn'

[WebServer]
AllowOrigins = '\*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[[EVM]]
ChainID = '80001'

[[EVM.Nodes]]
Name = 'Mumbai'
WSURL = 'wss://polygon-mumbai.g.alchemy.com/v2/l9ELqCkaZRLXCUsFqfp9VTbCM3goVZmN'
HTTPURL = 'https://polygon-mumbai.g.alchemy.com/v2/l9ELqCkaZRLXCUsFqfp9VTbCM3goVZmN'

